### PR TITLE
Add worktree aliases

### PR DESCRIPTION
**Pull request by sQVe**
This PR adds one alias for `git worktree`. I think the `Gwt` or `gwt` makes sense - but if you have any better ideas I'm happy to change this.

### CODE REVIEW

**Comment by ericbn** [comment]
Hi @sQVe! I've been considering adding `git worktree` aliases too. Maybe we read the same article about it recently!  :- )

Since there are many commands, I was thinking of something like:
```
alias GWa='git worktree add'
alias GWA='git worktree add -ff'
alias GWl='git worktree list'
alias GWo='git worktree lock'
alias GWu='git worktree unlock'
alias GWm='git worktree move'
alias GWM='git worktree move -ff'
alias GWp='git worktree prune'
alias GWx='git worktree remove'
alias GWX='git worktree remove -ff'
alias GWr='git worktree repair'
```

Still not sure about the `W` for it. Also not sure about `o`/`u` for lock/unlock. And not sure if the "double-force" aliases are useful, or if any other option is commonly used...

**Comment by sQVe** [comment]
This PR actually started as something similar but ended up like this. Largely due to the simple API of worktrees and lack of options.

The workflow when using worktrees is mainly `add`, `remove` and maybe `list` - so I'm sort of leaning towards that this is enough.

**Comment by ericbn** [comment]
Oh, cool! Can you please add the corresponding documentation to the README.md? Maybe something like
```
  * `Gwt` manages multiple working trees.
```

**Comment by sQVe** [comment]
Yes, of course. I totally forgot about the readme. I'll do that first thing tomorrow! 👍

**Comment by ericbn** [comment]
Giving this a second thought, I don't think we have any other alias that still requires typing an extra verb to have a complete command, so in this sense I think starting with `GWa`, `GWl` and `GWx` is better than having to type `Gwt add`, `Gwt list` and `Gwt remove`...

**Comment by sQVe** [comment]
You're right, and I totally agree. I do mirror your feelings about the aliases for `lock` and `unlock` though, the mnemonic just feels off...

**Comment by sQVe** [comment]
@ericbn I've now updated the PR.

I think the `lock` and `unlock` aliases might be fine - I tried to think of alternatives but it's kind of hard since there's quite a lot of commands under the scope of `worktree`. 

Another thing worth considering is the working tree headers and comments. I'm using **Managing multiple working trees** for `git worktree` which descriptive and separates it from the other **Working tree** section. If you have any better ideas, happy to hear them!

**Comment by sQVe** [comment]
A thing that is commonly used when using `worktree` is `--detach` since you can't checkout branches that's already checked out by another work tree. This is really sane defaults and I feel that the `-f` options should be replaced by `--detach`.

Instead of making a dangerous command it would then detach the **HEAD** at the branch you're inputting, which is likely what you'd want in many cases. 

What do you think?

**Comment by ericbn** [comment]
I'm not using the `worktree` feature yet, so I don't have a work flow for it. Let's start with aliases for the most basic commands then. Maybe just for `add`, `remove` and `list` as you initially mentioned. I saw articles mentioning `add -b`, `move` and `prune` too.

**Comment by sQVe** [comment]
Yeah, I'll simplify it a bit later and then we can iterate over it.

I'll add `add`, `remove`, `move`, `list` and `prune`. That will cover most of worktrees usage.

**Comment by ericbn** [comment]
Did a few changes: named the sections "Main working tree" and "Working trees", removed the `GWX` alias (so we postpone the decision to have 1 or 2 `-f` in it), and changed the descriptions a little bit.

Are you good with it so it can be merged?

**Comment by sQVe** [comment]
Awesome. Go for it! 👊

**Pull request merged**
